DROP DATABASE IF EXISTS PORTARIA;
CREATE DATABASE PORTARIA;
USE PORTARIA;

CREATE TABLE MORADOR (
ID_MORADOR INT AUTO_INCREMENT NOT NULL,
NOME_MORADOR VARCHAR(50),
CPF_MORADOR VARCHAR(14),
IDADE_MORADOR INT,
NUM_CONDOMINIO INT,
NUM_BLOCO INT,
VAGA_ESTACIONAMENTO BOOLEAN,
DT_CADASTRO TIMESTAMP,
PRIMARY KEY (ID_MORADOR)
);

CREATE TABLE FUNCIONARIO (
ID_FUNCIONARIO INT AUTO_INCREMENT NOT NULL,
NOME_FUNCIONARIO VARCHAR(50),
CPF_FUNCIONARIO VARCHAR(14),
IDADE_FUNCIONARIO INT,
EMAIL_FUNCIONARIO VARCHAR(50),
SENHA_FUNCIONARIO VARCHAR(50),
IS_ADM BOOLEAN,
PRIMARY KEY (ID_FUNCIONARIO)
);


-- Funcionários ADM
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("GABRIEL ALVES", "812.401.070-64", 20, "gabrielalves@portaria.com", "gab123", TRUE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("JOAO YONÉA", "706.129.610-01", 20, "joaoyonea@portaria.com", "joao123", TRUE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("RAFAEL SOARES", "674.918.530-48", 20, "rafaelsoares@portaria.com", "rafa123", TRUE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("ROBERTA DUPRAT", "705.869.390-08", 20, "robertaduprat@portaria.com", "rob123", TRUE);

-- Funcionários N/ADM
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("GABRIEL SOUZA", "025.296.120-05", 20, "gabrielsouza@portaria.com", "gabsouza123", FALSE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("JOAO FERREIRA", "003.898.040-10", 30, "joaoferreira@portaria.com", "jferreira123", FALSE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("RAFAEL ALMEIDA", "133.968.180-32", 22, "rafaelalmeida@portaria.com", "rafaalmeida123", FALSE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("ROBERTA DE CAMPOS", "131.752.940-57", 25, "robertacampos@portaria.com", "rcampos123", FALSE);

INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("GABRIEL VIANNA", "763.923.040-37", 28, "gabrielvianna@portaria.com", "gabvianna123", FALSE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("JOAO ANDERSON", "867.906.640-09", 19, "joaoanderson@portaria.com", "janderson123", FALSE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("RAFAEL TÁRTARO", "475.442.660-60", 21, "rafaeltartaro@portaria.com", "rafatartaro123", FALSE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("ROBERTA JONES", "756.970.350-20", 20, "robertajones@portaria.com", "robjones123", FALSE);

INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("GABRIEL TEXAS", "393.684.020-27", 32, "gabrieltexas@portaria.com", "gabtexas123", FALSE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("JOAO EDUARDO", "290.154.960-80", 26, "joaoeduardo@portaria.com", "joaoedu123", FALSE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("RAFAEL GONZALES", "100.181.460-66", 25, "rafaelgonzales@portaria.com", "rafagonzales123", FALSE);
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, CPF_FUNCIONARIO, IDADE_FUNCIONARIO, EMAIL_FUNCIONARIO, SENHA_FUNCIONARIO, IS_ADM) VALUES("ROBERTA BORGES", "774.850.840-20", 23, "robertaborges@portaria.com", "rborges123", FALSE);


-- Moradores
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("ELIZA BENSAÚDE CACHÃO", "162.564.960-60", 44, 1, 1, TRUE, "2022-05-31 12:00:00");
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("MAIRA PONTES LACERDA", "482.801.940-53", 32, 2, 1, FALSE, "2022-05-29 12:00:00");
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("ELIAS MILHEIRÃO MADUREIRA", "466.435.720-61", 25, 3, 1, TRUE, "2022-05-29 09:38:00");

INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("SANTHIAGO LAMPREIA FÉLIX", "668.523.640-03", 47, 4, 1, TRUE, "2022-05-31 10:13:45");
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("MAXIMIANO CHARNECA GODINHO", "635.279.980-98", 28, 1, 2, TRUE, "2022-05-31 13:22:06");
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("ADRIAN TRISTÃO CARVALHAL", "070.585.530-92", 19, 2, 2, TRUE, "2022-04-25 12:00:00");

INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("MATILDA DURÃES SOVERAL", "382.774.150-52", 63, 3, 2, FALSE, "2022-05-30 13:30:00");
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("ARIANA GUSMÃO VIGÁRIO", "334.524.160-97", 33, 4, 2, TRUE, "2022-05-30 13:32:17");
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("MARIA CASQUEIRA TALHÃO", "773.950.120-46", 27, 1, 3, FALSE, "2022-05-31 16:09:22");

INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("ARIEL GUERRA FREITAS", "300.883.940-18", 18, 2, 3, FALSE, "2022-05-29 12:12:00");
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("SANTHIAGO PAIÃO FILGUEIRAS", "094.210.390-41", 26, 3, 3, TRUE, "2022-05-29 15:44:34");
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("ADRIANO LOUSADO PARDO", "331.076.490-74", 32, 4, 3, TRUE, "2022-05-29 17:23:44");

INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("ELISEU SARDO BAIÃO", "172.101.420-96", 21, 1, 4, FALSE, "2022-05-28 10:12:30");
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("MAX CAVADAS VELASCO", "873.411.720-29", 36, 2, 4, FALSE, "2022-05-28 14:32:00");
INSERT INTO MORADOR(NOME_MORADOR, CPF_MORADOR, IDADE_MORADOR, NUM_CONDOMINIO, NUM_BLOCO, VAGA_ESTACIONAMENTO, DT_CADASTRO) VALUES("MAXILIAN SACRAMENTO PITEIRA", "352.222.200-87", 38, 3, 4, FALSE, "2022-04-26 13:23:30");



SELECT * FROM FUNCIONARIO;
SELECT * FROM MORADOR